name: Build and Deploy Angular 20

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22  # You can adjust the Node.js version as needed

    - name: Install dependencies
      run: npm install --legacy-peer-deps
      working-directory: sources

    - name: Build Angular project
      run: npm run build
      working-directory: sources

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: angular-build
        path: sources/dist

#    - name: Call URL
#      run: curl -X GET https://webhook.adena.dev/hooks/gender-utikalauz-deploy
